const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

// Load environment variables from .env.local
try {
  const envPath = path.resolve(process.cwd(), '.env.local');
  if (fs.existsSync(envPath)) {
    const envConfig = fs.readFileSync(envPath, 'utf8');
    envConfig.split('\n').forEach(line => {
      const [key, value] = line.split('=');
      if (key && value) {
        process.env[key.trim()] = value.trim();
      }
    });
  }
} catch (e) {
  console.warn('Could not load .env.local', e);
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing Supabase credentials in environment variables.');
  console.error('Please ensure .env.local exists and contains NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function generateSchema() {
  console.log('Fetching modules from database...');

  // Fetch all modules
  // Assuming 'modulos' table exists and has 'id'
  const { data: modules, error } = await supabase
    .from('modulos')
    .select('id')
    .order('created_at', { ascending: true }); // Or use 'orden' if available

  if (error) {
    console.error('Error fetching modules:', error);
    process.exit(1);
  }

  const moduleIds = modules.map(m => m.id);

  const fileContent = `// This file is auto-generated by scripts/generate_course_schema.js
// Do not edit manually unless you know what you are doing.

export const esquemaCursos = {
  totalModules: ${moduleIds.length},
  modules: ${JSON.stringify(moduleIds, null, 2)},
  // Future: courses: {} as Record<string, string[]>
};
`;

  const outputPath = path.resolve(process.cwd(), 'src/lib/academy/course-schema.ts');
  fs.writeFileSync(outputPath, fileContent);

  console.log(`Schema generated successfully with ${moduleIds.length} modules.`);
  console.log(`Saved to: ${outputPath}`);
}

generateSchema().catch(console.error);
