
import json

terms = [
    {"term": "Abalizar", "definition": "Marcar con boyas o balizas los pasos o peligros de la navegación.", "category": "maniobras"},
    {"term": "Abatimiento", "definition": "Desvío del rumbo que sufre la embarcación por efecto del viento.", "category": "meteorología"},
    {"term": "Abordar", "definition": "Entrar en colisión una embarcación con otra. También llegar, tocar o chocar una embarcación con el muelle.", "category": "maniobras"},
    {"term": "Acastillaje", "definition": "Conjunto de accesorios de cubierta (motones, cornamusas, etc.).", "category": "partes del barco"},
    {"term": "Acechar", "definition": "Vigilar el horizonte o la costa.", "category": "maniobras"},
    {"term": "Acuartelar", "definition": "Presentar al viento la superficie de una vela, llevando su puño de escota a barlovento.", "category": "maniobras"},
    {"term": "Adrizar", "definition": "Poner el barco derecho (vertical) cuando está escorado.", "category": "maniobras"},
    {"term": "Aferrar", "definition": "Recoger una vela y sujetarla para que no se abra.", "category": "maniobras"},
    {"term": "Agarrar", "definition": "Dicho del ancla, cuando se clava en el fondo.", "category": "maniobras"},
    {"term": "Aleta", "definition": "Parte curva del costado del buque en las proximidades de la popa.", "category": "partes del barco"},
    {"term": "Alíseos", "definition": "Vientos constantes que soplan en las zonas tórridas de Este a Oeste.", "category": "meteorología"},
    {"term": "Amante", "definition": "Cabo grueso que, firme en el extremo de una percha, sirve para suspenderla o moverla.", "category": "partes del barco"},
    {"term": "Amantillo", "definition": "Cabo que sirve para mantener, subir o bajar la botavara o el tangón.", "category": "partes del barco"},
    {"term": "Amarra", "definition": "Cabo, cable o cadena que sirve para sujetar el barco al muelle o a otra embarcación.", "category": "partes del barco"},
    {"term": "Amollar", "definition": "Soltar un poco de cabo o escota.", "category": "maniobras"},
    {"term": "Amura", "definition": "Parte curva del costado del buque en las proximidades de la proa.", "category": "partes del barco"},
    {"term": "Anclar", "definition": "Echar el ancla para que el barco quede sujeto al fondo.", "category": "maniobras"},
    {"term": "Anemómetro", "definition": "Instrumento para medir la velocidad del viento.", "category": "meteorología"},
    {"term": "Aparejo", "definition": "Conjunto de palos, vergas, jarcias y velas de un buque.", "category": "partes del barco"},
    {"term": "Aproar", "definition": "Poner la proa al viento o a un lugar determinado.", "category": "maniobras"},
    {"term": "Arboladura", "definition": "Conjunto de palos, masteleros y vergas de un buque.", "category": "partes del barco"},
    {"term": "Ardiente", "definition": "Dícese del barco que tiende a orzar.", "category": "maniobras"},
    {"term": "Arriar", "definition": "Bajar las velas, banderas o cualquier cosa que esté suspendida.", "category": "maniobras"},
    {"term": "Arriluze", "definition": "Muelle y zona de Getxo donde se encuentra la Escuela.", "category": "otros"},
    {"term": "Arrufadura", "definition": "Curvatura longitudinal de la cubierta alta o de la quilla.", "category": "partes del barco"},
    {"term": "Arrancada", "definition": "Inercia que lleva el barco cuando se mueve.", "category": "maniobras"},
    {"term": "As de guía", "definition": "Nudo marinero básico que forma una gaza fija y segura.", "category": "maniobras"},
    {"term": "Atracar", "definition": "Arrimar el barco a un muelle o a otra embarcación para amarrarse.", "category": "maniobras"},
    {"term": "Azimut", "definition": "Ángulo que forma el meridiano con la visual de un astro u objeto.", "category": "maniobras"},
    {"term": "Babor", "definition": "Costado izquierdo del barco mirando de popa a proa.", "category": "partes del barco"},
    {"term": "Baliza", "definition": "Señal fija o flotante para indicar peligros o canales de navegación.", "category": "reglamento"},
    {"term": "Ballestrinque", "definition": "Nudo muy útil para afirmar un cabo a una percha o argolla.", "category": "maniobras"},
    {"term": "Banda", "definition": "Cada uno de los costados del barco.", "category": "partes del barco"},
    {"term": "Barlovento", "definition": "Lugar o parte desde donde sopla el viento.", "category": "meteorología"},
    {"term": "Barómetro", "definition": "Instrumento para medir la presión atmosférica.", "category": "meteorología"},
    {"term": "Bauprés", "definition": "Palo que sale de la proa con cierta inclinación hacia arriba.", "category": "partes del barco"},
    {"term": "Bita", "definition": "Pieza sólida de metal o madera afirmada en cubierta para amarrar cabos.", "category": "partes del barco"},
    {"term": "Bitácora", "definition": "Armario o caja fija a la cubierta donde va montado el compás.", "category": "partes del barco"},
    {"term": "Borda", "definition": "Parte superior del costado del barco.", "category": "partes del barco"},
    {"term": "Bornear", "definition": "Girar el barco fondeado por efecto del viento o la corriente.", "category": "maniobras"},
    {"term": "Botavara", "definition": "Percha horizontal que sujeta el pujamen de la vela mayor.", "category": "partes del barco"},
    {"term": "Boyante", "definition": "Dícese del barco que no está calado hasta su línea de carga máxima.", "category": "maniobras"},
    {"term": "Braza", "definition": "Cabo que sirve para orientar las vergas o el tangón.", "category": "partes del barco"},
    {"term": "Brazola", "definition": "Reborde alto alrededor de la bañera o escotillas para impedir la entrada de agua.", "category": "partes del barco"},
    {"term": "Brújula", "definition": "Instrumento que sirve para determinar el rumbo (Compás).", "category": "partes del barco"},
    {"term": "Buque", "definition": "Barco de grandes dimensiones y solidez.", "category": "partes del barco"},
    {"term": "Cabecear", "definition": "Movimiento del barco de proa a popa por efecto del oleaje.", "category": "maniobras"},
    {"term": "Cable", "definition": "Medida de longitud náutica equivalente a la décima parte de una milla (185,2 metros).", "category": "maniobras"},
    {"term": "Cabullería", "definition": "Conjunto de cabos de un barco.", "category": "partes del barco"},
    {"term": "Cadenote", "definition": "Pieza metálica unida al casco donde se afirman los obenques.", "category": "partes del barco"},
    {"term": "Caer", "definition": "Desviar el rumbo hacia una banda.", "category": "maniobras"},
    {"term": "Caja de orza", "definition": "Abertura en el casco por donde sube y baja la orza.", "category": "partes del barco"},
    {"term": "Calado", "definition": "Profundidad que alcanza la parte sumergida del barco.", "category": "partes del barco"},
    {"term": "Campeche", "definition": "Zona de navegación o tipo de madera, pero en contexto local puede referirse a un punto geográfico.", "category": "otros"},
    {"term": "Candeleros", "definition": "Barras metálicas verticales que sostienen los guardamancebos.", "category": "partes del barco"},
    {"term": "Capear", "definition": "Aguantar un temporal proa al mar con poca vela.", "category": "maniobras"},
    {"term": "Carro", "definition": "Riel por donde se desplaza la escota de la mayor o el foque.", "category": "partes del barco"},
    {"term": "Carta náutica", "definition": "Mapa utilizado para la navegación.", "category": "maniobras"},
    {"term": "Casco", "definition": "Cuerpo del barco sin contar arboladura ni superestructuras.", "category": "partes del barco"},
    {"term": "Catamarán", "definition": "Embarcación de dos cascos.", "category": "partes del barco"},
    {"term": "Cazar", "definition": "Cobrar o tensar un cabo, generalmente una escota.", "category": "maniobras"},
    {"term": "Ceñir", "definition": "Navegar contra el viento con el menor ángulo posible.", "category": "maniobras"},
    {"term": "Centro vélico", "definition": "Punto donde se considera aplicada la fuerza total del viento sobre las velas.", "category": "maniobras"},
    {"term": "Chaleco salvavidas", "definition": "Elemento de seguridad personal obligatorio.", "category": "reglamento"},
    {"term": "Ciabogar", "definition": "Hacer girar la embarcación sobre sí misma mediante la máquina o los remos.", "category": "maniobras"},
    {"term": "Ciar", "definition": "Dar marcha atrás.", "category": "maniobras"},
    {"term": "Cobrar", "definition": "Recoger o tirar de un cabo.", "category": "maniobras"},
    {"term": "Codaste", "definition": "Pieza estructural que cierra el casco por la popa.", "category": "partes del barco"},
    {"term": "Compás", "definition": "Instrumento magnético o electrónico que indica el rumbo.", "category": "partes del barco"},
    {"term": "Contra", "definition": "Aparejo que impide que la botavara suba.", "category": "partes del barco"},
    {"term": "Cornamusa", "definition": "Pieza con dos brazos para amarrar cabos.", "category": "partes del barco"},
    {"term": "Correr", "definition": "Navegar con el viento y las olas por la popa durante un temporal.", "category": "maniobras"},
    {"term": "Costado", "definition": "Cada uno de los lados del casco del barco.", "category": "partes del barco"},
    {"term": "Coz", "definition": "Extremo de la botavara que se une al mástil.", "category": "partes del barco"},
    {"term": "Crujía", "definition": "Línea imaginaria que divide el barco en dos mitades simétricas de proa a popa.", "category": "partes del barco"},
    {"term": "Cubierta", "definition": "Suelo exterior del barco que cierra el casco por arriba.", "category": "partes del barco"},
    {"term": "Cunningham", "definition": "Aparejo para tensar el grátil de la vela mayor.", "category": "maniobras"},
    {"term": "Deriva", "definition": "Desplazamiento lateral de la embarcación por efecto de la corriente.", "category": "maniobras"},
    {"term": "Derrota", "definition": "Trayectoria seguida por la embarcación.", "category": "maniobras"},
    {"term": "Desalar", "definition": "Volcar una embarcación de vela ligera. (También 'Volcar').", "category": "maniobras"},
    {"term": "Descuartelar", "definition": "Rumbo entre el través y la ceñida.", "category": "maniobras"},
    {"term": "Driza", "definition": "Cabo utilizado para izar las velas.", "category": "partes del barco"},
    {"term": "Drizar", "definition": "Izar las velas.", "category": "maniobras"},
    {"term": "Duarte", "definition": "Viento del Oeste en la zona del estrecho.", "category": "meteorología"},
    {"term": "Ecosonda", "definition": "Aparato que mide la profundidad del fondo mediante ondas sonoras.", "category": "partes del barco"},
    {"term": "Empopada", "definition": "Navegar con el viento entrando directamente por la popa.", "category": "maniobras"},
    {"term": "Encalmarse", "definition": "Quedarse sin viento.", "category": "meteorología"},
    {"term": "Enfilación", "definition": "Línea visual que une dos objetos fijos y sirve para situarse.", "category": "maniobras"},
    {"term": "Escandallo", "definition": "Instrumento antiguo para medir la profundidad (plomo y cordel).", "category": "partes del barco"},
    {"term": "Escoben", "definition": "Agujero en la proa por donde pasa la cadena del ancla.", "category": "partes del barco"},
    {"term": "Escora", "definition": "Inclinación lateral del barco.", "category": "maniobras"},
    {"term": "Escota", "definition": "Cabo que sirve para cazar y orientar las velas.", "category": "partes del barco"},
    {"term": "Escotilla", "definition": "Abertura en la cubierta para acceder al interior.", "category": "partes del barco"},
    {"term": "Eslora", "definition": "Longitud del barco.", "category": "partes del barco"},
    {"term": "Espejo de popa", "definition": "Parte plana o ligeramente curva que cierra la popa.", "category": "partes del barco"},
    {"term": "Espigón", "definition": "Muro construido para proteger un puerto del oleaje.", "category": "otros"},
    {"term": "Estay", "definition": "Cable que sujeta el mástil desde proa.", "category": "partes del barco"},
    {"term": "Estela", "definition": "Rastro que deja el barco en el agua al navegar.", "category": "maniobras"},
    {"term": "Estribor", "definition": "Costado derecho del barco mirando de popa a proa.", "category": "partes del barco"},
    {"term": "Faltar", "definition": "Romperse un cabo o cadena.", "category": "maniobras"},
    {"term": "Filástica", "definition": "Cada una de las fibras o hilos que forman un cabo.", "category": "partes del barco"},
    {"term": "Filar", "definition": "Arriar progresivamente un cabo o cadena.", "category": "maniobras"},
    {"term": "Fondeadero", "definition": "Lugar apto para fondear.", "category": "maniobras"},
    {"term": "Fondear", "definition": "Anclar la embarcación.", "category": "maniobras"},
    {"term": "Foque", "definition": "Vela triangular que se monta en proa.", "category": "partes del barco"},
    {"term": "Forro", "definition": "Parte exterior del casco.", "category": "partes del barco"},
    {"term": "Francobordo", "definition": "Distancia vertical desde la línea de flotación hasta la cubierta principal.", "category": "partes del barco"},
    {"term": "Galerna", "definition": "Temporal súbito y violento típico del Cantábrico.", "category": "meteorología"},
    {"term": "Garrear", "definition": "Arrastrar el ancla por el fondo sin que agarre.", "category": "maniobras"},
    {"term": "Gato", "definition": "Dispositivo mecánico para tensar cabos o elevar pesos.", "category": "partes del barco"},
    {"term": "Gavia", "definition": "Vela cuadra que va sobre la mayor en los grandes veleros.", "category": "partes del barco"},
    {"term": "Gaza", "definition": "Ojo o lazo hecho en el extremo de un cabo.", "category": "partes del barco"},
    {"term": "Génova", "definition": "Vela de proa de gran tamaño que sobrepasa el mástil.", "category": "partes del barco"},
    {"term": "Gobierno", "definition": "Acción de dirigir el barco.", "category": "maniobras"},
    {"term": "Grátil", "definition": "Borde de la vela que se sujeta al palo o al estay.", "category": "partes del barco"},
    {"term": "Grillete", "definition": "Pieza metálica en forma de U con un perno, usada para unir elementos.", "category": "partes del barco"},
    {"term": "Guardamancebos", "definition": "Cables o cabos que pasan por los candeleros para seguridad.", "category": "partes del barco"},
    {"term": "Guiñada", "definition": "Desvío involuntario del rumbo.", "category": "maniobras"},
    {"term": "Hélice", "definition": "Elemento propulsor del barco a motor.", "category": "partes del barco"},
    {"term": "Imbornal", "definition": "Agujero para dar salida al agua de la cubierta.", "category": "partes del barco"},
    {"term": "Izar", "definition": "Subir las velas o una bandera.", "category": "maniobras"},
    {"term": "Jarcia firme", "definition": "Conjunto de cables (obenques, estays) que sujetan los palos.", "category": "partes del barco"},
    {"term": "Jarcia de labor", "definition": "Conjunto de cabos (drizas, escotas) para manejar las velas.", "category": "partes del barco"},
    {"term": "Juanete", "definition": "Vela que va sobre la gavia.", "category": "partes del barco"},
    {"term": "Largar", "definition": "Soltar totalmente un cabo.", "category": "maniobras"},
    {"term": "Lastre", "definition": "Peso que se pone en el fondo del barco o en la quilla para aumentar la estabilidad.", "category": "partes del barco"},
    {"term": "Latina", "definition": "Vela triangular usada en embarcaciones tradicionales.", "category": "partes del barco"},
    {"term": "Lazareto", "definition": "Lugar para guardar pertrechos o provisiones.", "category": "partes del barco"},
    {"term": "Línea de crujía", "definition": "Eje longitudinal del barco.", "category": "partes del barco"},
    {"term": "Línea de flotación", "definition": "Línea que separa la obra viva de la obra muerta.", "category": "partes del barco"},
    {"term": "Línea de vida", "definition": "Cinta o cable a lo largo de la cubierta para asegurarse con el arnés.", "category": "reglamento"},
    {"term": "Lozas", "definition": "Sinónimo antiguo de piedras o rocas en el fondo.", "category": "otros"},
    {"term": "Luces de navegación", "definition": "Luces reglamentarias para navegar de noche.", "category": "reglamento"},
    {"term": "Lumbrera", "definition": "Abertura con cristal para dar luz al interior.", "category": "partes del barco"},
    {"term": "Manga", "definition": "Anchura máxima del barco.", "category": "partes del barco"},
    {"term": "Maniobra", "definition": "Operación que se hace a bordo para el gobierno o manejo del buque.", "category": "maniobras"},
    {"term": "Marcación", "definition": "Ángulo entre el norte y la visual a un objeto.", "category": "maniobras"},
    {"term": "Marea", "definition": "Movimiento periódico de ascenso y descenso del nivel del mar.", "category": "meteorología"},
    {"term": "Mástil", "definition": "Palo vertical que soporta las velas.", "category": "partes del barco"},
    {"term": "Mayor", "definition": "Vela principal del barco.", "category": "partes del barco"},
    {"term": "Milla náutica", "definition": "Unidad de distancia igual a 1852 metros.", "category": "maniobras"},
    {"term": "Mora", "definition": "Retraso en la ejecución de una maniobra (poco usado hoy día).", "category": "otros"},
    {"term": "Mordaza", "definition": "Mecanismo para fijar un cabo rápidamente.", "category": "partes del barco"},
    {"term": "Mosquetón", "definition": "Gancho metálico con cierre de resorte.", "category": "partes del barco"},
    {"term": "Motón", "definition": "Polea por donde pasan los cabos.", "category": "partes del barco"},
    {"term": "Navegación", "definition": "Ciencia y arte de conducir una embarcación.", "category": "maniobras"},
    {"term": "Nudo", "definition": "Unidad de velocidad equivalente a una milla náutica por hora.", "category": "maniobras"},
    {"term": "Obenque", "definition": "Cable que sujeta el mástil lateralmente.", "category": "partes del barco"},
    {"term": "Obra muerta", "definition": "Parte del casco que está fuera del agua.", "category": "partes del barco"},
    {"term": "Obra viva", "definition": "Parte del casco sumergida en el agua.", "category": "partes del barco"},
    {"term": "Ojo de buey", "definition": "Ventana circular en el costado del barco.", "category": "partes del barco"},
    {"term": "Orza", "definition": "Pieza plana y lastrada que sobresale bajo la quilla para evitar el abatimiento.", "category": "partes del barco"},
    {"term": "Orzar", "definition": "Dirigir la proa hacia el viento (cerrar el ángulo).", "category": "maniobras"},
    {"term": "Pajarín", "definition": "Cabo que tensa el pujamen de la mayor hacia la popa.", "category": "partes del barco"},
    {"term": "Pañol", "definition": "Compartimento para guardar velas, cabos, pinturas, etc.", "category": "partes del barco"},
    {"term": "Pasteca", "definition": "Motón o polea que se puede abrir lateralmente.", "category": "partes del barco"},
    {"term": "Patrón", "definition": "Persona que manda la embarcación.", "category": "reglamento"},
    {"term": "Pernos", "definition": "Tornillos grandes que sujetan la quilla al casco.", "category": "partes del barco"},
    {"term": "Pie de gallo", "definition": "Ramificación de un cabo en dos o más.", "category": "partes del barco"},
    {"term": "Plan", "definition": "Piso inferior de la embarcación.", "category": "partes del barco"},
    {"term": "Pleamar", "definition": "Momento de máxima altura de la marea.", "category": "meteorología"},
    {"term": "Popa", "definition": "Parte posterior del barco.", "category": "partes del barco"},
    {"term": "Portulano", "definition": "Colección de planos de puertos.", "category": "otros"},
    {"term": "Proa", "definition": "Parte delantera del barco.", "category": "partes del barco"},
    {"term": "Pujamen", "definition": "Borde inferior de la vela.", "category": "partes del barco"},
    {"term": "Puntal", "definition": "Altura del buque desde la quilla hasta la cubierta.", "category": "partes del barco"},
    {"term": "Puño de amura", "definition": "Ángulo inferior de proa de la vela.", "category": "partes del barco"},
    {"term": "Puño de drisa", "definition": "Ángulo superior de la vela por donde se iza.", "category": "partes del barco"},
    {"term": "Puño de escota", "definition": "Ángulo inferior de popa de la vela.", "category": "partes del barco"},
    {"term": "Quebranto", "definition": "Deformación del casco por arrufo excesivo.", "category": "partes del barco"},
    {"term": "Quilla", "definition": "Pieza estructural longitudinal en la parte más baja del casco.", "category": "partes del barco"},
    {"term": "Radiobaliza", "definition": "Dispositivo de emergencia que emite señales de socorro vía satélite.", "category": "reglamento"},
    {"term": "Raquero", "definition": "Barco escuela colectivo usado habitualmente en vela ligera.", "category": "otros"},
    {"term": "Regala", "definition": "Pieza que cubre la borda por su parte superior.", "category": "partes del barco"},
    {"term": "Relinga", "definition": "Cuerda cosida en los bordes de las velas para reforzarlas o introducirlas en el mástil.", "category": "partes del barco"},
    {"term": "Remolcar", "definition": "Tirar de una embarcación mediante un cabo.", "category": "maniobras"},
    {"term": "Respeto", "definition": "Material de repuesto (ancla de respeto, caña de respeto).", "category": "reglamento"},
    {"term": "Retenida", "definition": "Cabo para impedir que la botavara cambie de banda violentamente.", "category": "maniobras"},
    {"term": "Rida", "definition": "Cada uno de los cabos que tensan los obenques (antiguamente). Ahora tensores.", "category": "partes del barco"},
    {"term": "Rizo", "definition": "Disminución de la superficie de la vela mediante cabos llamados tomadores de rizos.", "category": "maniobras"},
    {"term": "Roda", "definition": "Pieza que forma la proa del barco, continuación de la quilla.", "category": "partes del barco"},
    {"term": "Role", "definition": "Cambio en la dirección del viento.", "category": "meteorología"},
    {"term": "Rosa de los vientos", "definition": "Círculo que tiene marcados los 32 rumbos o cuartas del horizonte.", "category": "otros"},
    {"term": "Rumbo", "definition": "Dirección en la que navega el barco.", "category": "maniobras"},
    {"term": "Sable", "definition": "Varilla que se introduce en la vela para darle forma y rigidez.", "category": "partes del barco"},
    {"term": "Sargazo", "definition": "Alga marina que puede dificultar la navegación.", "category": "otros"},
    {"term": "Sextante", "definition": "Instrumento para medir la altura de los astros y situarse.", "category": "maniobras"},
    {"term": "Sonda", "definition": "Profundidad del agua en un lugar. También el instrumento para medirla.", "category": "maniobras"},
    {"term": "Sotavento", "definition": "Lado contrario a donde viene el viento.", "category": "meteorología"},
    {"term": "Spy (Spinnaker)", "definition": "Vela de balón para navegar con vientos portantes.", "category": "partes del barco"},
    {"term": "Tangón", "definition": "Percha que sirve para atangonar (separar) el puño de escota del foque o spinnaker.", "category": "partes del barco"},
    {"term": "Telera", "definition": "Caja o estuche para guardar banderas.", "category": "partes del barco"},
    {"term": "Templar", "definition": "Equilibrar la tensión de los cabos o velas.", "category": "maniobras"},
    {"term": "Temporal", "definition": "Viento fuerte, generalmente acompañado de lluvia y oleaje.", "category": "meteorología"},
    {"term": "Tensor", "definition": "Elemento roscado para dar tensión a los obenques y estays.", "category": "partes del barco"},
    {"term": "Timón", "definition": "Pieza plana articulada en la popa que sirve para dirigir el barco.", "category": "partes del barco"},
    {"term": "Tope", "definition": "Extremo superior del mástil.", "category": "partes del barco"},
    {"term": "Trabujada", "definition": "Maniobra de cambio de amura en vientos portantes (Virada en redondo involuntaria o controlada).", "category": "maniobras"},
    {"term": "Trinquete", "definition": "Palo de proa en barcos de más de un palo.", "category": "partes del barco"},
    {"term": "Tripulación", "definition": "Conjunto de personas que manejan el barco.", "category": "otros"},
    {"term": "Unidad", "definition": "Barco o embarcación considerada individualmente.", "category": "otros"},
    {"term": "Vagra", "definition": "Pieza longitudinal de refuerzo en el fondo del casco.", "category": "partes del barco"},
    {"term": "Vahído", "definition": "Cambio ligero y momentáneo del viento.", "category": "meteorología"},
    {"term": "Varada", "definition": "Acción de encallar o sacar el barco a tierra.", "category": "maniobras"},
    {"term": "Vela", "definition": "Superficie de tela que recibe el viento para propulsar el barco.", "category": "partes del barco"},
    {"term": "Velamen", "definition": "Conjunto de velas de un barco.", "category": "partes del barco"},
    {"term": "Verga", "definition": "Percha horizontal cruzada en el palo para sostener velas cuadras.", "category": "partes del barco"},
    {"term": "Vía de agua", "definition": "Entrada de agua en el casco por rotura o avería.", "category": "maniobras"},
    {"term": "Viento aparente", "definition": "Suma vectorial del viento real y el viento generado por la velocidad del barco.", "category": "meteorología"},
    {"term": "Viento real", "definition": "El que sopla en la atmósfera independientemente del movimiento del barco.", "category": "meteorología"},
    {"term": "Vigía", "definition": "Persona encargada de vigilar el horizonte.", "category": "otros"},
    {"term": "Virar", "definition": "Cambiar de rumbo cruzando la línea del viento.", "category": "maniobras"},
    {"term": "Virazón", "definition": "Viento térmico que sopla del mar hacia tierra durante el día.", "category": "meteorología"},
    {"term": "Winche", "definition": "Torno para cazar escotas o drizas con menos esfuerzo.", "category": "partes del barco"},
    {"term": "Yate", "definition": "Embarcación de recreo.", "category": "otros"},
    {"term": "Zafar", "definition": "Librar, desembarazar o soltar algo.", "category": "maniobras"},
    {"term": "Zozobrar", "definition": "Volcar o irse a pique por fuerza del viento o mar.", "category": "maniobras"},
    {"term": "Zurcir", "definition": "Reparar una vela cosiendo.", "category": "maniobras"},
]

# Adding more terms to reach ~200
extra_terms = [
    {"term": "Abofetear", "definition": "Golpear las velas contra el palo por falta de viento o mala maniobra.", "category": "maniobras"},
    {"term": "Abra", "definition": "Bahía o ensenada donde pueden fondear los barcos.", "category": "meteorología"},
    {"term": "Aclarar", "definition": "Desenrollar o desenmarañar cabos.", "category": "maniobras"},
    {"term": "Acoderar", "definition": "Dar una amarra a una boya o ancla por la popa para mantener el barco en una posición determinada.", "category": "maniobras"},
    {"term": "Adujar", "definition": "Recoger un cabo en vueltas o adujas.", "category": "maniobras"},
    {"term": "Aguas jurisdiccionales", "definition": "Zona marítima bajo soberanía de un estado.", "category": "reglamento"},
    {"term": "Aguas someras", "definition": "Aguas poco profundas.", "category": "meteorología"},
    {"term": "Ahocicar", "definition": "Meter la proa en el agua al bajar la ola.", "category": "maniobras"},
    {"term": "Alargar", "definition": "Alejarse de la costa o de otro barco.", "category": "maniobras"},
    {"term": "Alcázar", "definition": "Parte de la cubierta superior entre el palo mayor y la popa.", "category": "partes del barco"},
    {"term": "Alma", "definition": "Parte central de un cabo o cable.", "category": "partes del barco"},
    {"term": "Almirantazgo", "definition": "Tipo de ancla clásica con cepo.", "category": "partes del barco"},
    {"term": "Alta mar", "definition": "Parte del mar alejada de la costa y fuera de las aguas territoriales.", "category": "reglamento"},
    {"term": "Alunamiento", "definition": "Curvatura del borde de salida de una vela (baluma).", "category": "partes del barco"},
    {"term": "Amadrinar", "definition": "Unir dos barcos costado con costado.", "category": "maniobras"},
    {"term": "Amarinar", "definition": "Dar carácter marinero a la tripulación o al barco.", "category": "otros"},
    {"term": "Andana", "definition": "Varios barcos atracados uno al costado del otro.", "category": "maniobras"},
    {"term": "Anillo", "definition": "Argolla.", "category": "partes del barco"},
    {"term": "Aparejar", "definition": "Poner los aparejos necesarios para navegar.", "category": "maniobras"},
    {"term": "Aplacerado", "definition": "Fondo del mar llano y de poca profundidad.", "category": "meteorología"},
    {"term": "Apante", "definition": "Dícese del barco que apenas avanza.", "category": "maniobras"},
    {"term": "Arganeo", "definition": "Grillete o anilla grande del ancla donde se afirma la cadena.", "category": "partes del barco"},
    {"term": "Arraigado", "definition": "Punto fijo donde se hace firme un cabo o cable.", "category": "partes del barco"},
    {"term": "Arribada", "definition": "Llegada de un buque a puerto, forzosa o voluntaria.", "category": "maniobras"},
    {"term": "Arribar", "definition": "Alejar la proa de la dirección del viento (abrir el rumbo).", "category": "maniobras"},
    {"term": "Arranchar", "definition": "Preparar el barco para enfrentar mal tiempo (son de mar).", "category": "maniobras"},
    {"term": "Asiento", "definition": "Diferencia entre el calado de popa y el de proa.", "category": "maniobras"},
    {"term": "Atangonar", "definition": "Separar una vela con el tangón.", "category": "maniobras"},
    {"term": "Aterraje", "definition": "Aproximación a tierra.", "category": "maniobras"},
    {"term": "Atracada", "definition": "Maniobra de atracar.", "category": "maniobras"},
    {"term": "Aura", "definition": "Viento suave y apacible.", "category": "meteorología"},
    {"term": "Avante", "definition": "Hacia adelante.", "category": "maniobras"},
    {"term": "Avistar", "definition": "Ver algo en el horizonte.", "category": "maniobras"},
    {"term": "Ayustar", "definition": "Unir dos cabos por sus chicotes mediante costura o nudo.", "category": "maniobras"},
    {"term": "Bajamar", "definition": "Nivel más bajo de la marea.", "category": "meteorología"},
    {"term": "Balance", "definition": "Movimiento oscilatorio transversal del barco.", "category": "maniobras"},
    {"term": "Baluma", "definition": "Borde de salida de la vela (de puño de driza a puño de escota).", "category": "partes del barco"},
    {"term": "Banco", "definition": "Bajo de arena o piedra en el mar.", "category": "meteorología"},
    {"term": "Bañera", "definition": "Espacio abierto en popa donde se sitúa la caña o rueda del timón.", "category": "partes del barco"},
    {"term": "Barloventear", "definition": "Avanzar hacia donde sopla el viento dando bordadas.", "category": "maniobras"},
    {"term": "Batayola", "definition": "Barandilla en la borda.", "category": "partes del barco"},
    {"term": "Bichero", "definition": "Palo con un gancho en la punta para agarrar cabos, boyas, etc.", "category": "partes del barco"},
    {"term": "Bigote", "definition": "Ola que forma la proa al avanzar.", "category": "maniobras"},
    {"term": "Bitadura", "definition": "Porción de cadena preparada para fondear.", "category": "maniobras"},
    {"term": "Bocina", "definition": "Orificio por donde sale el eje de la hélice al exterior.", "category": "partes del barco"},
    {"term": "Bolina", "definition": "Cabo para cazar la caída de barlovento de las velas cuadras. Navegar de bolina es ceñir.", "category": "maniobras"},
    {"term": "Bote", "definition": "Embarcación pequeña sin cubierta.", "category": "partes del barco"},
    {"term": "Botón", "definition": "Nudo en el extremo de un cabo para que no se deshaga.", "category": "maniobras"},
    {"term": "Boyar", "definition": "Mantenerse a flote.", "category": "maniobras"},
    {"term": "Bozas", "definition": "Cabos para amarrar el bote auxiliar o asegurar el ancla.", "category": "partes del barco"},
    {"term": "Braza", "definition": "Unidad de medida de profundidad (1,83 metros).", "category": "maniobras"},
    {"term": "Brazos", "definition": "Partes del ancla que terminan en las uñas.", "category": "partes del barco"},
    {"term": "Broma", "definition": "Molusco que perfora la madera de los barcos.", "category": "otros"},
    {"term": "Bruma", "definition": "Niebla que se levanta del mar.", "category": "meteorología"},
    {"term": "Buque escuela", "definition": "Barco destinado a la enseñanza práctica de la navegación.", "category": "otros"},
    {"term": "Cabilla", "definition": "Pieza de madera o metal para amarrar cabos en el cabillero.", "category": "partes del barco"},
    {"term": "Cabo", "definition": "Cualquier cuerda usada a bordo. También punta de tierra que entra en el mar.", "category": "partes del barco"},
    {"term": "Cabotaje", "definition": "Navegación costera entre puertos de un mismo país.", "category": "reglamento"},
    {"term": "Cachete", "definition": "Golpe de mar que rompe contra el costado.", "category": "maniobras"},
    {"term": "Cajera", "definition": "Abertura en una polea o mástil por donde pasa un cabo.", "category": "partes del barco"},
    {"term": "Calafatear", "definition": "Tapar las juntas de las tablas del casco con estopa y brea.", "category": "maniobras"},
    {"term": "Calina", "definition": "Bruma seca y calurosa.", "category": "meteorología"},
    {"term": "Camareta", "definition": "Habitáculo pequeño o camarote común.", "category": "partes del barco"},
    {"term": "Camarote", "definition": "Dormitorio en un barco.", "category": "partes del barco"},
    {"term": "Canal", "definition": "Vía de agua navegable natural o artificial.", "category": "maniobras"},
    {"term": "Cáncamo", "definition": "Tornillo con ojo o argolla.", "category": "partes del barco"},
    {"term": "Candela", "definition": "Poner el palo en candela es ponerlo vertical.", "category": "maniobras"},
    {"term": "Caña", "definition": "Palanca unida a la mecha del timón para gobernarlo.", "category": "partes del barco"},
    {"term": "Capa", "definition": "Maniobra de seguridad con mal tiempo (Ponerse a la capa).", "category": "maniobras"},
    {"term": "Capitán", "definition": "Máxima autoridad a bordo.", "category": "reglamento"},
    {"term": "Carajera", "definition": "Saco o caja para guardar las drizas y escotas en la bañera.", "category": "partes del barco"},
    {"term": "Carina", "definition": "Parte sumergida del casco (obra viva).", "category": "partes del barco"},
    {"term": "Carta de navegación", "definition": "Mapa marino.", "category": "maniobras"},
    {"term": "Catalina", "definition": "Rueda de la pasteca o motón.", "category": "partes del barco"},
    {"term": "Cayo", "definition": "Isla pequeña y llana de arena.", "category": "meteorología"},
    {"term": "Celaje", "definition": "Aspecto del cielo.", "category": "meteorología"},
    {"term": "Cenit", "definition": "Punto del cielo vertical sobre la cabeza del observador.", "category": "maniobras"},
    {"term": "Cepo", "definition": "Barra transversal del ancla tipo almirantazgo.", "category": "partes del barco"},
    {"term": "Cerrazón", "definition": "Oscuridad del cielo por nubes o niebla.", "category": "meteorología"},
    {"term": "Chalana", "definition": "Embarcación pequeña de fondo plano.", "category": "partes del barco"},
    {"term": "Chicote", "definition": "Extremo de un cabo.", "category": "partes del barco"},
    {"term": "Chinchorro", "definition": "Bote auxiliar pequeño.", "category": "partes del barco"},
    {"term": "Chumacera", "definition": "Pieza donde apoya el remo para bogar.", "category": "partes del barco"},
    {"term": "Cia", "definition": "Orden de remar hacia atrás.", "category": "maniobras"},
    {"term": "Ciclón", "definition": "Borrasca tropical muy intensa.", "category": "meteorología"},
    {"term": "Cintón", "definition": "Refuerzo longitudinal que protege el costado.", "category": "partes del barco"},
    {"term": "Ciar", "definition": "Remar o dar máquina hacia atrás.", "category": "maniobras"},
    {"term": "Clase", "definition": "Categoría de barcos de diseño idéntico (ej. Clase J80).", "category": "otros"},
    {"term": "Cobrar", "definition": "Recoger cabo.", "category": "maniobras"},
    {"term": "Codera", "definition": "Cabo que se da por la popa o aleta para mantener el barco atravesado.", "category": "maniobras"},
    {"term": "Cofa", "definition": "Plataforma en lo alto de los palos.", "category": "partes del barco"},
    {"term": "Combés", "definition": "Espacio en cubierta entre el palo mayor y el castillo de proa.", "category": "partes del barco"},
    {"term": "Compás de demoras", "definition": "Instrumento para tomar marcaciones a la costa.", "category": "maniobras"},
    {"term": "Compensar", "definition": "Ajustar el compás para corregir el desvío.", "category": "maniobras"},
    {"term": "Condiciones", "definition": "Estado del mar y viento.", "category": "meteorología"},
    {"term": "Conocimiento", "definition": "Documento de embarque o flete.", "category": "reglamento"},
    {"term": "Conserva", "definition": "Navegar en compañía de otro barco.", "category": "maniobras"},
    {"term": "Contramaestre", "definition": "Jefe de la marinería.", "category": "reglamento"},
    {"term": "Convoy", "definition": "Conjunto de buques mercantes escoltados.", "category": "otros"},
    {"term": "Cornamusas", "definition": "Piezas para amarrar cabos.", "category": "partes del barco"},
    {"term": "Corredera", "definition": "Instrumento para medir la velocidad del barco y distancia navegada.", "category": "maniobras"},
    {"term": "Corriente", "definition": "Movimiento de la masa de agua del mar.", "category": "meteorología"},
    {"term": "Costear", "definition": "Navegar cerca de la costa.", "category": "maniobras"},
    {"term": "Costillas", "definition": "Cuadernas del barco.", "category": "partes del barco"},
    {"term": "Cote", "definition": "Nudo sencillo.", "category": "maniobras"},
    {"term": "Cuaderna", "definition": "Pieza curva que forma las costillas del casco.", "category": "partes del barco"},
    {"term": "Cuadernal", "definition": "Bloque con varias roldanas o poleas.", "category": "partes del barco"},
    {"term": "Cuadrante", "definition": "Cada una de las cuatro partes en que se divide el horizonte o la rosa de los vientos.", "category": "otros"},
    {"term": "Cuarentena", "definition": "Aislamiento preventivo de un buque.", "category": "reglamento"},
    {"term": "Cuartear", "definition": "Nombrar los rumbos de la rosa de los vientos.", "category": "maniobras"},
    {"term": "Cubichete", "definition": "Tapa que protege el compás o una ventilación.", "category": "partes del barco"},
    {"term": "Culebrina", "definition": "Cabo delgado.", "category": "partes del barco"},
    {"term": "Cuna", "definition": "Soporte para varar el barco en tierra.", "category": "otros"},
    {"term": "Curso", "definition": "Dirección o trayectoria.", "category": "maniobras"},
    {"term": "Dársena", "definition": "Parte resguardada artificialmente en un puerto para fondeo o carga.", "category": "otros"},
    {"term": "Declinación", "definition": "Diferencia angular entre el Norte Geográfico y el Magnético.", "category": "maniobras"},
    {"term": "Defensas", "definition": "Elementos amortiguadores que se colocan en el costado para protegerlo al atracar.", "category": "partes del barco"},
    {"term": "Demora", "definition": "Ángulo entre el Norte y la visual a un objeto.", "category": "maniobras"},
    {"term": "Derecho de paso", "definition": "Preferencia de una embarcación sobre otra según el reglamento.", "category": "reglamento"},
    {"term": "Derrelicto", "definition": "Casco de buque abandonado y a la deriva.", "category": "otros"},
    {"term": "Desabrigado", "definition": "Lugar sin protección contra el viento o mar.", "category": "meteorología"},
    {"term": "Desarbolar", "definition": "Perder los palos por rotura.", "category": "maniobras"},
    {"term": "Desatraque", "definition": "Maniobra inversa al atraque.", "category": "maniobras"},
    {"term": "Desvío", "definition": "Error del compás producido por los hierros del propio barco.", "category": "maniobras"},
    {"term": "Dique", "definition": "Muro de contención del agua o instalación para reparar barcos en seco.", "category": "otros"},
    {"term": "Draga", "definition": "Barco para limpiar o ahondar fondos.", "category": "otros"},
    {"term": "Ducha", "definition": "Lluvia breve y pasajera.", "category": "meteorología"},
    {"term": "Durmiente", "definition": "Pieza longitudinal donde apoyan los baos de la cubierta.", "category": "partes del barco"},
    {"term": "Eje", "definition": "Barra que transmite el movimiento del motor a la hélice.", "category": "partes del barco"},
    {"term": "Embarrancar", "definition": "Quedar el barco varado en el fondo.", "category": "maniobras"},
    {"term": "Embestir", "definition": "Chocar violentamente.", "category": "maniobras"},
    {"term": "Embrear", "definition": "Untar con brea.", "category": "maniobras"},
    {"term": "Empavesado", "definition": "Adorno del buque con banderas en días festivos.", "category": "otros"},
    {"term": "Encalmar", "definition": "Quedar el barco sin viento.", "category": "meteorología"},
    {"term": "Encapilladura", "definition": "Extremo superior del palo donde se fijan los obenques y estays.", "category": "partes del barco"},
    {"term": "Encepar", "definition": "Enredarse la cadena en el cepo o uña del ancla.", "category": "maniobras"},
    {"term": "Enjaretado", "definition": "Rejilla de madera que sirve de piso.", "category": "partes del barco"},
    {"term": "Entalingar", "definition": "Unir la cadena al ancla.", "category": "maniobras"},
    {"term": "Entra la mar", "definition": "Expresión cuando el oleaje invade la cubierta.", "category": "meteorología"},
    {"term": "Escala", "definition": "Escalera de cuerda o madera.", "category": "partes del barco"},
    {"term": "Escandalosa", "definition": "Vela triangular que se iza por encima de la cangreja.", "category": "partes del barco"},
    {"term": "Escarceo", "definition": "Movimiento agitado de la mar por corrientes encontradas.", "category": "meteorología"},
    {"term": "Escoben", "definition": "Conducto de salida de la cadena.", "category": "partes del barco"},
    {"term": "Escobén", "definition": "Orificio en la proa para el paso de cables o cadena.", "category": "partes del barco"},
    {"term": "Escollera", "definition": "Dique de defensa formado por piedras.", "category": "otros"},
    {"term": "Escollo", "definition": "Peñasco a flor de agua o poco sumergido.", "category": "meteorología"},
    {"term": "Eslinga", "definition": "Cabo o cable con gazas para levantar cargas.", "category": "maniobras"},
    {"term": "Espía", "definition": "Cabo que se da a un objeto firme para mover el barco.", "category": "maniobras"},
    {"term": "Estacha", "definition": "Cabo grueso para remolque o amarre.", "category": "partes del barco"},
    {"term": "Estanqueidad", "definition": "Cualidad de no dejar pasar el agua.", "category": "partes del barco"},
    {"term": "Estrave", "definition": "Parte de la roda.", "category": "partes del barco"},
    {"term": "Estrepada", "definition": "Tirón violento.", "category": "maniobras"},
    {"term": "Falucho", "definition": "Embarcación costera de vela latina.", "category": "otros"},
    {"term": "Fanal", "definition": "Farol grande o faro.", "category": "partes del barco"},
    {"term": "Farallón", "definition": "Roca alta y tajada que sobresale en el mar.", "category": "meteorología"},
    {"term": "Faro", "definition": "Torre con luz para guiar a los navegantes.", "category": "reglamento"},
    {"term": "Ferretería", "definition": "Conjunto de piezas metálicas del aparejo.", "category": "partes del barco"},
    {"term": "Flete", "definition": "Precio del transporte marítimo.", "category": "otros"},
    {"term": "Flotabilidad", "definition": "Capacidad de flotar.", "category": "maniobras"},
    {"term": "Fogonadura", "definition": "Orificio en cubierta por donde pasa el palo.", "category": "partes del barco"},
    {"term": "Fondo", "definition": "Suelo del mar.", "category": "meteorología"},
    {"term": "Fragata", "definition": "Buque de guerra de tres palos.", "category": "otros"},
    {"term": "Fraile", "definition": "Pieza solida de amarre en proa.", "category": "partes del barco"},
    {"term": "Franco", "definition": "Libre de obstáculos (Viento franco: favorable).", "category": "maniobras"},
    {"term": "Frenillo", "definition": "Cabo que une los obenques.", "category": "partes del barco"},
    {"term": "Fresachón", "definition": "Viento fuerte (Fuerza 6 o 7).", "category": "meteorología"},
    {"term": "Fresco", "definition": "Viento moderado (Fuerza 5).", "category": "meteorología"},
    {"term": "Gabarra", "definition": "Barcaza de transporte en puerto.", "category": "otros"},
    {"term": "Galleta", "definition": "Sombrerete del tope del palo.", "category": "partes del barco"},
    {"term": "Gallardete", "definition": "Bandera estrecha y larga.", "category": "otros"},
    {"term": "Garrucho", "definition": "Anillo o gancho para fijar la vela al estay.", "category": "partes del barco"},
    {"term": "Gatera", "definition": "Orificio para el paso de la cadena del ancla o cabos.", "category": "partes del barco"},
    {"term": "Girocompás", "definition": "Brújula no magnética basada en un giróscopo.", "category": "partes del barco"},
    {"term": "Goleta", "definition": "Velero de dos o más palos con velas cangrejas.", "category": "otros"},
    {"term": "Grada", "definition": "Instalación para construir o reparar barcos.", "category": "otros"},
    {"term": "Grampín", "definition": "Ancla pequeña de cuatro uñas (rezón).", "category": "partes del barco"},
    {"term": "Grandes Velas", "definition": "Velas principales.", "category": "partes del barco"},
    {"term": "Gratil", "definition": "Lado de la vela que se une al palo.", "category": "partes del barco"},
    {"term": "Guindaleza", "definition": "Cabo grueso.", "category": "partes del barco"},
    {"term": "Guindar", "definition": "Subir algo a lo alto.", "category": "maniobras"},
    {"term": "Guiñar", "definition": "Alterar el rumbo a una y otra banda.", "category": "maniobras"},
    {"term": "Guitarra", "definition": "Freno de cabos con palanca.", "category": "partes del barco"},
    {"term": "Habilitación", "definition": "Locales habitables del buque.", "category": "partes del barco"},
    {"term": "Halar", "definition": "Tirar de un cabo.", "category": "maniobras"},
    {"term": "Hembra", "definition": "Parte del timón donde encaja el macho.", "category": "partes del barco"},
    {"term": "Hocicar", "definition": "Hundir la proa.", "category": "maniobras"},
    {"term": "Hombre al agua", "definition": "Emergencia por caída de una persona al mar.", "category": "maniobras"},
    {"term": "Horquilla", "definition": "Soporte para los remos.", "category": "partes del barco"},
    {"term": "Huracán", "definition": "Viento de fuerza extraordinaria (Fuerza 12).", "category": "meteorología"},
    {"term": "Imbornales", "definition": "Agujeros de desagüe.", "category": "partes del barco"},
    {"term": "Inbornal", "definition": "Variante de imbornal.", "category": "partes del barco"},
    {"term": "Inteligencia", "definition": "Bandera de señales (gallardete característico).", "category": "reglamento"},
    {"term": "Isobara", "definition": "Línea que une puntos de igual presión atmosférica.", "category": "meteorología"},
    {"term": "Jabeque", "definition": "Embarcación mediterránea de tres palos.", "category": "otros"},
    {"term": "Jarcia", "definition": "Conjunto de cabos y cables.", "category": "partes del barco"},
    {"term": "Jorfe", "definition": "Pared vertical de costa.", "category": "meteorología"},
    {"term": "Jareta", "definition": "Cabo que pasa por una costura.", "category": "partes del barco"},
]

all_terms = terms + extra_terms

# Deduplicate by term name
unique_terms = {}
for t in all_terms:
    unique_terms[t['term']] = t

sorted_terms = sorted(unique_terms.values(), key=lambda x: x['term'])

# Generate TypeScript content
ts_content = """import { NauticalTerm } from '@/types/glossary';

export const nauticalTerms: NauticalTerm[] = [
"""

for i, term in enumerate(sorted_terms):
    course_slug = ""
    # Add logic for course links if needed
    if "Vela Ligera" in term['definition'] or term['category'] == "maniobras":
         course_slug = ", relatedCourseSlug: 'vela-ligera'"
    elif "Licencia" in term['definition'] or term['category'] == "reglamento":
         course_slug = ", relatedCourseSlug: 'licencia-navegacion'"
    elif "J80" in term['definition'] or "crucero" in term['definition']:
         course_slug = ", relatedCourseSlug: 'iniciacion-j80'"

    ts_content += f"""    {{
        id: 'term-{i+1}',
        term: "{term['term']}",
        definition: "{term['definition']}",
        category: '{term['category']}'{course_slug}
    }},
"""

ts_content += "];\n"

with open('src/data/nauticalGlossary.ts', 'w') as f:
    f.write(ts_content)

print(f"Generated {len(sorted_terms)} terms.")
